# Generated by Django 4.1.3 on 2022-12-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('fechaNac', models.DateField()),
                ('curso', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('horario', models.DateTimeField(max_length=60)),
                ('dias', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('sobre', models.CharField(max_length=500)),
                ('cursos', models.CharField(max_length=60)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
